[package]
name = "fuzzer-libfuzzer"
version = "0.0.1"
publish = false

[features]
default = ["protobuf-codec"]
protobuf-codec = ["fuzz-targets/protobuf-codec"]
prost-codec = ["fuzz-targets/prost-codec"]

[dependencies]
fuzz-targets = { path = "../targets", default-features = false }
libfuzzer-sys = "0.3.1"
